name: Build and Release LuCI

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  PACKAGE_NAME: luci-app-xray
  CACHE_DIR: ~/cache

jobs:
  release:
    name: Build for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            sdk_url: https://downloads.openwrt.org/releases/25.12.2/targets/x86/64/openwrt-sdk-25.12.2-x86-64_gcc-14.3.0_musl.Linux-x86_64.tar.zst
          - arch: aarch64_cortex-a53
            sdk_url: https://downloads.openwrt.org/releases/25.12.2/targets/mediatek/filogic/openwrt-sdk-25.12.2-mediatek-filogic_gcc-14.3.0_musl.Linux-x86_64.tar.zst
          - arch: aarch64_cortex-a72
            sdk_url: https://downloads.openwrt.org/releases/25.12.2/targets/mvebu/cortexa72/openwrt-sdk-25.12.2-mvebu-cortexa72_gcc-14.3.0_musl.Linux-x86_64.tar.zst
          - arch: arm_cortex-a7_neon-vfpv4
            sdk_url: https://downloads.openwrt.org/releases/25.12.2/targets/bcm27xx/bcm2709/openwrt-sdk-25.12.2-bcm27xx-bcm2709_gcc-14.3.0_musl_eabi.Linux-x86_64.tar.zst
          - arch: aarch64_generic
            sdk_url: https://downloads.openwrt.org/releases/25.12.2/targets/rockchip/armv8/openwrt-sdk-25.12.2-rockchip-armv8_gcc-14.3.0_musl.Linux-x86_64.tar.zst

    env:
      CCACHE_DIR: ~/.ccache
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y ccache gettext libncurses5-dev xsltproc p7zip-full

      - name: Prepare SDK
        run: |
          mkdir -p "$CACHE_DIR/sdk"
          cd "$CACHE_DIR/sdk"
          SDK_FILE=$(basename ${{ matrix.sdk_url }})
          wget -q ${{ matrix.sdk_url }} -O $SDK_FILE
          mkdir -p "$GITHUB_WORKSPACE/sdk_home"
          tar --zstd -xf $SDK_FILE --strip-components=1 -C "$GITHUB_WORKSPACE/sdk_home"
          echo "SDK_HOME=$GITHUB_WORKSPACE/sdk_home" >> $GITHUB_ENV

      - name: Prepare Feeds and Package
        run: |
          cd "$SDK_HOME"
          # Не трогаем git.openwrt.org
          ./scripts/feeds update -a
          ln -s "${{ github.workspace }}" "package/$PACKAGE_NAME"
          ./scripts/feeds install -a

      - name: Build LuCI Package
        run: |
          cd "$SDK_HOME"
          make defconfig
          make package/$PACKAGE_NAME/compile V=s
          cp bin/packages/*/*/$PACKAGE_NAME*.apk "${{ github.workspace }}/"
          cd -

      - name: List built APKs
        run: ls -lh "${{ github.workspace }}/"*.apk

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.apk"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
